module NaturalNumbers.Everything where

import NaturalNumbers.Utils
import NaturalNumbers.Syntax
import NaturalNumbers.Embeddings
import NaturalNumbers.Conversion
import NaturalNumbers.OPE 
import NaturalNumbers.OPELemmas
import NaturalNumbers.IdentityEnvironment
--
import NaturalNumbers.RecursiveNormaliser
import NaturalNumbers.OPERecursive
import NaturalNumbers.StrongConvertibility
import NaturalNumbers.Soundness
--
import NaturalNumbers.BigStepSemantics
import NaturalNumbers.OPEBigStep
import NaturalNumbers.StructuralNormaliser 
import NaturalNumbers.StrongComputability
import NaturalNumbers.TerminationandCompleteness
