module NaturalNumbers.Everything where

import NaturalNumbers.Utils
import NaturalNumbers.Syntax
import NaturalNumbers.Conversion
import NaturalNumbers.OPE 
import NaturalNumbers.OPELemmas
--
import NaturalNumbers.RecursiveNormaliser
--
import NaturalNumbers.BigStepSemantics
import NaturalNumbers.OPEBigStep
import NaturalNumbers.StrongComputability
import NaturalNumbers.StructuralNormaliser
import NaturalNumbers.StabilityAndCompleteness
import NaturalNumbers.StrongConvertibility
import NaturalNumbers.Soundness
