module FiniteProducts.Everything where

import FiniteProducts.Utils
import FiniteProducts.Syntax
import FiniteProducts.Conversion
import FiniteProducts.OPE 
import FiniteProducts.OPELemmas
--
import FiniteProducts.RecursiveNormalizer
--
import FiniteProducts.BigStepSemantics
import FiniteProducts.OPEBigStep
import FiniteProducts.StrongComputability
import FiniteProducts.StructuralNormalizer
import FiniteProducts.StabilityAndCompleteness
import FiniteProducts.StrongConvertibility
import FiniteProducts.Soundness
